apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlinkedingresses.awsblueprints.io
spec:
  group: awsblueprints.io
  names:
    kind: XLinkedIngress
    plural: xlinkedingresses
  claimNames:
    kind: LinkedIngress
    plural: linkedingresses
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                resourceConfig:
                  type: object
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                  required:
                    - providerConfigName
                fqdn:
                  type: string
                hostedZoneId:
                  type: string
                zoneId:
                  type: string
                serviceName:
                  type: string
              type: object
              required:
                - resourceConfig
                - fqdn
                - hostedZoneId
                - zoneId
                - serviceName

