apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlinkedingress.awsblueprints.io
spec:
  group: awsblueprints.io
  names:
    kind: XLinkedIngress
    plural: xlinkedingresses
  claimNames:
    kind: LinkedIngress
    plural: linkedingresses
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                fqdn:
                  type: string
                hostedZoneId:
                  type: string
                zoneId:
                  type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value provided by this field.
                      type: string
                    namespace:
                      description: The namespace where all the resources for this composition should live
                      type: string
                    serviceName:
                      description: Name of the service to link the ingress to (in same namespace)
                      type: string
                    providerConfigName:
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                          - key
                          - value
                        type: object
                      type: array
                  required:
                    - providerConfigName
                    - tags
                  type: object
              required:
                - resourceConfig
                - hostedZoneId
                - zoneId
                - fqdn